# c_compiler:
#   - clang  # [win]
# c_compiler_version:
#   - 17  # [win]
rust_compiler:
  - rust
rust_compiler_version:
  - 1.76.0.dev20231115
MACOSX_DEPLOYMENT_TARGET:
  - 10.12  # [osx and x86_64]