{% set name = "polars" %}
{% set version = "1.38.1" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 803a2be5344ef880ad625addfb8f641995cfd777413b08a10de0897345778239
  - url: https://github.com/pola-rs/{{ name }}/archive/refs/tags/py-{{ version }}.tar.gz
    sha256: c3004449abf0026b892db8100153aa6053ecd0c122917154106f2733aae099b4
    folder: gh
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-runtime-32/{{ name }}_runtime_32-{{ version }}.tar.gz
    sha256: 04f20ed1f5c58771f34296a27029dc755a9e4b1390caeaef8f317e06fdfce2ec
    folder: polars-runtime-32
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-runtime-64/{{ name }}_runtime_64-{{ version }}.tar.gz
    sha256: ac53eefbad39614806ee9c7ff93564983e1821fb8331dc4b2a7c53bdc0804056
    folder: polars-runtime-64
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-runtime-compat/{{ name }}_runtime_compat-{{ version }}.tar.gz
    sha256: 7ae7d98fcddd309a14d194d921fcfba867e84ea792a24c37f981c27cba7d26db
    folder: polars-runtime-compat

build:
  number: 0
  skip: True  # [py<39]

requirements:
  host:
    - pip
    - python
  run:
    - python

outputs:
  - name: polars-runtime-32
    script: build_runtime.sh   # [not win]
    script: build_runtime.bat  # [win]
    requirements:
      build:
        - {{ stdlib('c') }}  # [linux]
        - {{ compiler('c') }}  # [linux]
        - {{ compiler('cxx') }}  # [linux]
        - rust-nightly 1.94.0_2026_01_09
        - cargo-auditable
        - cargo-bundle-licenses
      host:
        - pip
        - python
        - maturin >=1.3.2,<2
      run:
        - python
    test:
      imports:
        - _polars_runtime_32
      requires:
        - pip
      commands:
        - pip check
    about:
      home: https://www.pola.rs
      license: MIT
      license_family: MIT
      license_file:
        - polars-runtime-32/LICENSE
        - polars-runtime-32/THIRDPARTY.yml
      summary: Polars is a blazingly fast DataFrames library implemented in Rust using Apache Arrow(2) as memory model.
      description: |
        Polars is a blazingly fast DataFrame library for manipulating structured data. The core is written in Rust, and
        available for Python, R and NodeJS.
        Key features:
          * Fast: Written from scratch in Rust, designed close to the machine and without external dependencies.
          * I/O: First class support for all common data storage layers: local, cloud storage & databases.
          * Intuitive API: Write your queries the way they were intended. Polars, internally, will determine the most efficient way to execute using its query optimizer.
          * Out of Core: The streaming API allows you to process your results without requiring all your data to be in memory at the same time
          * Parallel: Utilities the power of your machine by dividing the workload among the available CPU cores without any additional configuration.
          * Vectorized Query Engine: Using Apache Arrow, a columnar data format, to process your queries in a vectorized manner and SIMD to optimize CPU usage.
      doc_url: https://docs.pola.rs/api/python/stable/reference/index.html
      dev_url: https://github.com/pola-rs/polars
  - name: polars-runtime-64
    script: build_runtime.sh   # [not win]
    script: build_runtime.bat  # [win]
    requirements:
      build:
        - {{ stdlib('c') }}  # [linux]
        - {{ compiler('c') }}  # [linux]
        - {{ compiler('cxx') }}  # [linux]
        - rust-nightly 1.94.0_2026_01_09
        - cargo-auditable
        - cargo-bundle-licenses
      host:
        - pip
        - python
        - maturin >=1.3.2,<2
      run:
        - python
    test:
      imports:
        - _polars_runtime_64
      requires:
        - pip
      commands:
        - pip check
    about:
      home: https://www.pola.rs
      license: MIT
      license_family: MIT
      license_file:
        - polars-runtime-64/LICENSE
        - polars-runtime-64/THIRDPARTY.yml
      summary: Polars is a blazingly fast DataFrames library implemented in Rust using Apache Arrow(2) as memory model.
      description: |
        Polars is a blazingly fast DataFrame library for manipulating structured data. The core is written in Rust, and
        available for Python, R and NodeJS.
        Key features:
          * Fast: Written from scratch in Rust, designed close to the machine and without external dependencies.
          * I/O: First class support for all common data storage layers: local, cloud storage & databases.
          * Intuitive API: Write your queries the way they were intended. Polars, internally, will determine the most efficient way to execute using its query optimizer.
          * Out of Core: The streaming API allows you to process your results without requiring all your data to be in memory at the same time
          * Parallel: Utilities the power of your machine by dividing the workload among the available CPU cores without any additional configuration.
          * Vectorized Query Engine: Using Apache Arrow, a columnar data format, to process your queries in a vectorized manner and SIMD to optimize CPU usage.
      doc_url: https://docs.pola.rs/api/python/stable/reference/index.html
      dev_url: https://github.com/pola-rs/polars
  - name: polars-runtime-compat
    script: build_runtime.sh   # [not win]
    script: build_runtime.bat  # [win]
    requirements:
      build:
        - {{ stdlib('c') }}  # [linux]
        - {{ compiler('c') }}  # [linux]
        - {{ compiler('cxx') }}  # [linux]
        - rust-nightly 1.94.0_2026_01_09
        - cargo-auditable
        - cargo-bundle-licenses
      host:
        - pip
        - python
        - maturin >=1.3.2,<2
      run:
        - python
    test:
      imports:
        - _polars_runtime_compat
      requires:
        - pip
      commands:
        - pip check
    about:
      home: https://www.pola.rs
      license: MIT
      license_family: MIT
      license_file:
        - polars-runtime-compat/LICENSE
        - polars-runtime-compat/THIRDPARTY.yml
      summary: Polars is a blazingly fast DataFrames library implemented in Rust using Apache Arrow(2) as memory model.
      description: |
        Polars is a blazingly fast DataFrame library for manipulating structured data. The core is written in Rust, and
        available for Python, R and NodeJS.
        Key features:
          * Fast: Written from scratch in Rust, designed close to the machine and without external dependencies.
          * I/O: First class support for all common data storage layers: local, cloud storage & databases.
          * Intuitive API: Write your queries the way they were intended. Polars, internally, will determine the most efficient way to execute using its query optimizer.
          * Out of Core: The streaming API allows you to process your results without requiring all your data to be in memory at the same time
          * Parallel: Utilities the power of your machine by dividing the workload among the available CPU cores without any additional configuration.
          * Vectorized Query Engine: Using Apache Arrow, a columnar data format, to process your queries in a vectorized manner and SIMD to optimize CPU usage.
      doc_url: https://docs.pola.rs/api/python/stable/reference/index.html
      dev_url: https://github.com/pola-rs/polars
  - name: {{ name }}  
    script: build_polars.sh   # [not win]
    script: build_polars.bat  # [win]
    requirements:
      host:
        - pip
        - python
        - setuptools >=61
        - wheel
      run:
        - python
        - {{ pin_subpackage('polars-runtime-32', exact=True) }}
      run_constrained:
        - numpy >=1.16.0
        - pyarrow >=7.0.0
        - fastexcel >=0.9
        - openpyxl >=3.0.0
        - xlsx2csv >=0.8.0
        - connectorx >=0.3.2
        - deltalake >=1.0.0
        - pyiceberg >=0.7.1
        - altair >=5.4.0
        - great_tables >=0.8.0
        - polars-runtime-64 =={{ version }}
        - polars-runtime-compat =={{ version }}

    # ModuleNotFoundError: No module named 'deltalake'
    {% set ignore_tests = "--ignore=gh/py-polars/tests/unit/io/test_delta.py" %}
    # ModuleNotFoundError: No module named 'pyiceberg'
    {% set ignore_tests = ignore_tests + " --ignore=gh/py-polars/tests/unit/io/test_iceberg.py" %}   
    # _ ERROR collecting gh/py-polars/tests/unit/testing/parametric/strategies/test_utils.py _
    # import file mismatch:
    # imported module 'test_utils' has this __file__ attribute: 
    {% set ignore_tests = ignore_tests + " --ignore=gh/py-polars/tests/unit/io/test_write.py" %}
    {% set ignore_tests = ignore_tests + " --ignore=gh/py-polars/tests/unit/testing/parametric/strategies/test_utils.py" %}
    # ModuleNotFoundError: No module named 'kuzu'
    {% set ignore_tests = ignore_tests + " --ignore=gh/py-polars/tests/unit/io/database/test_read.py" %}
    # ModuleNotFoundError: required package 'fastexcel' not found
    {% set ignore_tests = ignore_tests + " --ignore=gh/py-polars/tests/unit/io/test_spreadsheet.py" %}

    # Number of modules are missing like xlsx2csv, fastexcel, connectorx
    {% set deselect_tests = "--deselect=gh/py-polars/tests/unit/io/cloud/test_credential_provider.py::test_credential_provider_rebuild_clears_cache" %}   
    {% set deselect_tests = deselect_tests + " --deselect=gh/py-polars/tests/unit/io/database/test_write.py::TestWriteDatabase::test_write_database_create[adbc-True]" %}   
    {% set deselect_tests = deselect_tests + " --deselect=gh/py-polars/tests/unit/io/database/test_write.py::TestWriteDatabase::test_write_database_create[adbc-False]" %}   
    {% set deselect_tests = deselect_tests + " --deselect=gh/py-polars/tests/unit/io/database/test_write.py::TestWriteDatabase::test_write_database_append_replace[adbc-True]" %}   
    {% set deselect_tests = deselect_tests + " --deselect=gh/py-polars/tests/unit/io/database/test_write.py::TestWriteDatabase::test_write_database_append_replace[adbc-False]" %}   
    {% set deselect_tests = deselect_tests + " --deselect=gh/py-polars/tests/unit/io/database/test_write.py::TestWriteDatabase::test_write_database_create_quoted_tablename[adbc-True]" %}   
    {% set deselect_tests = deselect_tests + " --deselect=gh/py-polars/tests/unit/io/database/test_write.py::TestWriteDatabase::test_write_database_create_quoted_tablename[adbc-False]" %}   
    {% set deselect_tests = deselect_tests + " --deselect=gh/py-polars/tests/unit/io/database/test_write.py::TestWriteDatabase::test_write_database_errors[adbc-True]" %}   
    {% set deselect_tests = deselect_tests + " --deselect=gh/py-polars/tests/unit/io/database/test_write.py::TestWriteDatabase::test_write_database_errors[adbc-False]" %}   
    {% set deselect_tests = deselect_tests + " --deselect=gh/py-polars/tests/unit/io/database/test_write.py::test_write_database_adbc_temporary_table" %}   
    {% set deselect_tests = deselect_tests + " --deselect=gh/py-polars/tests/unit/io/test_hive.py::test_hive_decode_reserved_ascii_23241" %}   
    {% set deselect_tests = deselect_tests + " --deselect=gh/py-polars/tests/unit/io/test_hive.py::test_hive_decode_utf8_23241" %} 
    {% set deselect_tests = deselect_tests + " --deselect=gh/py-polars/tests/unit/test_api.py::test_namespace_warning_on_override" %}   
    {% set deselect_tests = deselect_tests + " --deselect=gh/py-polars/tests/unit/test_ds_plugin.py::test_basic_operation" %}   
    {% set deselect_tests = deselect_tests + " --deselect=gh/py-polars/tests/unit/test_polars_import.py::test_polars_import" %}
    # AssertionError: Series are different (values not within tolerance)
    {% set deselect_tests = deselect_tests + " --deselect=gh/py-polars/tests/unit/operations/test_interpolate_by.py::test_interpolate_vs_numpy" %}
    # AssertionError: DataFrames are different (dtypes do not match)
    # [left]: [Int32, UInt32, UInt32]
    # [right]: [Int64, UInt32, UInt32]
    {% set deselect_tests = deselect_tests + " --deselect=gh/py-polars/tests/unit/operations/test_group_by.py::test_boolean_min_max_agg" %}  # [win]
    
    test:
      source_files:
        - gh/py-polars/tests
      imports:
        - polars
      commands:
        - pip check
        - pytest -v gh/py-polars/tests {{ ignore_tests }} {{ deselect_tests }}
      requires:
        - pip
        - pytest
        - flask
        - flask-cors
        - orjson
        - altair
        - pytorch
        - jax
        - hypothesis >=6.97.4
        - polars-runtime-32 =={{ version }}
        - pyarrow
        - pandas
        - boto3
        - sqlalchemy
        - moto
        - pydantic
        - zstandard
        - matplotlib
        - nest-asyncio
        - cloudpickle
        - fsspec
        - gevent
        - openpyxl >=3.0.0
        - pandas
        - hvplot >=0.9.1
        - pyarrow >=7.0.0
        - pydantic >=2.0.0
        - pyxlsb >=1.0  # [py<312]
        - sqlalchemy
        - backports.zoneinfo  # [py<39]
        - tzdata  # [win]
        - xlsxwriter
        - aiosqlite

about:
  home: https://www.pola.rs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Polars is a blazingly fast DataFrames library implemented in Rust using Apache Arrow(2) as memory model.
  description: |
    Polars is a blazingly fast DataFrame library for manipulating structured data. The core is written in Rust, and
    available for Python, R and NodeJS.
    Key features:
      * Fast: Written from scratch in Rust, designed close to the machine and without external dependencies.
      * I/O: First class support for all common data storage layers: local, cloud storage & databases.
      * Intuitive API: Write your queries the way they were intended. Polars, internally, will determine the most efficient way to execute using its query optimizer.
      * Out of Core: The streaming API allows you to process your results without requiring all your data to be in memory at the same time
      * Parallel: Utilities the power of your machine by dividing the workload among the available CPU cores without any additional configuration.
      * Vectorized Query Engine: Using Apache Arrow, a columnar data format, to process your queries in a vectorized manner and SIMD to optimize CPU usage.
  doc_url: https://docs.pola.rs/api/python/stable/reference/index.html
  dev_url: https://github.com/pola-rs/polars

extra:
  recipe-maintainers:
    - borchero
    - Maxyme
    - timkpaine
    - ritchie46
    - sugatoray
    - xhochy
    - dhirschfeld
    - pavelzw
    - '0xbe7a'
