{% set name = "polars" %}
{% set version = "0.18.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/polars-{{ version }}.tar.gz
    sha256: dbf0bdc0ec56d22041436a98b626f0667af6e700e3f4d5639c3c4f06eddf9e36

build:
  number: 0
  skip: true  # [py<38]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - posix                               # [win]
    - cmake
    - make                                # [unix]
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - maturin 1.1.0
  run:
    - python
    - numpy >=1.16.0
    - backports.zoneinfo                   # [py<39]
    - typing_extensions >=4.0.0            # [py<311]

test:
  imports:
    - polars
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pola-rs/polars
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Polars is a blazingly fast DataFrames library implemented in Rust using Apache Arrow(2) as memory model.
  doc_url: https://pola-rs.github.io/polars-book/user-guide/index.html
  dev_url: https://github.com/pola-rs/polars

extra:
  recipe-maintainers:
    - borchero
    - Maxyme
    - timkpaine
    - ritchie46
    - sugatoray
    - xhochy
    - dhirschfeld
