{% set name = "polars" %}
{% set version = "1.36.1" %}
{% set ignore_tests = "--ignore=gh/py-polars/tests/unit/io/test_delta.py" %}
{% set ignore_tests = ignore_tests + " --ignore=gh/py-polars/tests/unit/io/test_iceberg.py" %}
{% set ignore_tests = ignore_tests + " --ignore=gh/py-polars/tests/unit/io/test_write.py" %}
{% set ignore_tests = ignore_tests + " --ignore=gh/py-polars/tests/unit/testing/parametric/strategies/test_utils.py" %}
{% set ignore_tests = ignore_tests + " --ignore=gh/py-polars/tests/unit/io/database/test_read.py" %}
{% set ignore_tests = ignore_tests + " --ignore=gh/py-polars/tests/unit/io/test_spreadsheet.py" %}
{% set deselect_tests = "--deselect=gh/py-polars/tests/unit/io/cloud/test_credential_provider.py::test_credential_provider_rebuild_clears_cache" %}
{% set deselect_tests = 'deselect_tests + " --deselect=gh/py-polars/tests/unit/io/database/test_write.py::TestWriteDatabase::test_write_database_create[adbc-True]"' %}
{% set deselect_tests = 'deselect_tests + " --deselect=gh/py-polars/tests/unit/io/database/test_write.py::TestWriteDatabase::test_write_database_create[adbc-False]"' %}
{% set deselect_tests = 'deselect_tests + " --deselect=gh/py-polars/tests/unit/io/database/test_write.py::TestWriteDatabase::test_write_database_append_replace[adbc-True]"' %}
{% set deselect_tests = 'deselect_tests + " --deselect=gh/py-polars/tests/unit/io/database/test_write.py::TestWriteDatabase::test_write_database_append_replace[adbc-False]"' %}
{% set deselect_tests = 'deselect_tests + " --deselect=gh/py-polars/tests/unit/io/database/test_write.py::TestWriteDatabase::test_write_database_create_quoted_tablename[adbc-True]"' %}
{% set deselect_tests = 'deselect_tests + " --deselect=gh/py-polars/tests/unit/io/database/test_write.py::TestWriteDatabase::test_write_database_create_quoted_tablename[adbc-False]"' %}
{% set deselect_tests = 'deselect_tests + " --deselect=gh/py-polars/tests/unit/io/database/test_write.py::TestWriteDatabase::test_write_database_errors[adbc-True]"' %}
{% set deselect_tests = 'deselect_tests + " --deselect=gh/py-polars/tests/unit/io/database/test_write.py::TestWriteDatabase::test_write_database_errors[adbc-False]"' %}
{% set deselect_tests = 'deselect_tests + " --deselect=gh/py-polars/tests/unit/io/database/test_write.py::test_write_database_adbc_temporary_table"' %}
{% set deselect_tests = 'deselect_tests + " --deselect=gh/py-polars/tests/unit/io/test_hive.py::test_hive_decode_reserved_ascii_23241"' %}
{% set deselect_tests = 'deselect_tests + " --deselect=gh/py-polars/tests/unit/io/test_hive.py::test_hive_decode_utf8_23241"' %}
{% set deselect_tests = 'deselect_tests + " --deselect=gh/py-polars/tests/unit/test_api.py::test_namespace_warning_on_override"' %}
{% set deselect_tests = 'deselect_tests + " --deselect=gh/py-polars/tests/unit/test_ds_plugin.py::test_basic_operation"' %}
{% set deselect_tests = 'deselect_tests + " --deselect=gh/py-polars/tests/unit/test_polars_import.py::test_polars_import"' %}
{% set deselect_tests = 'deselect_tests + " --deselect=gh/py-polars/tests/unit/operations/test_interpolate_by.py::test_interpolate_vs_numpy"' %}
{% set deselect_tests = 'deselect_tests + " --deselect=gh/py-polars/tests/unit/operations/test_group_by.py::test_boolean_min_max_agg"' %}  # [win]

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 12c7616a2305559144711ab73eaa18814f7aa898c522e7645014b68f1432d54c
  - url: https://github.com/pola-rs/{{ name }}/archive/refs/tags/py-{{ version }}.tar.gz
    sha256: a7fc1221cfb7c77a1fbc346a7b3ca20ef37cb25bafea5dbb5b8e8ddf23e3aa0d
    folder: gh
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-runtime-32/{{ name }}_runtime_32-{{ version }}.tar.gz
    sha256: 201c2cfd80ceb5d5cd7b63085b5fd08d6ae6554f922bcb941035e39638528a09
    folder: polars-runtime-32
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-runtime-64/{{ name }}_runtime_64-{{ version }}.tar.gz
    sha256: e77144090cdd13c68f125117bcad5bb9dd2c2d892897785b3375a411b73300f5
    folder: polars-runtime-64
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}-runtime-compat/{{ name }}_runtime_compat-{{ version }}.tar.gz
    sha256: 276d5c262cb9086e27ba6fea88c95aa069c535117ce46299c665ded930befad0
    folder: polars-runtime-compat

build:
  number: 0
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
  run:
    - python

outputs:
  - name: polars-runtime-32
    script: build_runtime.sh  # [not win]
    script: build_runtime.bat  # [win]
    requirements:
      build:
        - {{ stdlib('c') }}  # [linux]
        - {{ compiler('c') }}  # [linux]
        - {{ compiler('cxx') }}  # [linux]
        - {{ compiler('rust-nightly') }}
        - cargo-auditable
        - cargo-bundle-licenses
      host:
        - pip
        - python
        - maturin >=1.3.2,<2
      run:
        - python
    test:
      imports:
        - _polars_runtime_32
      requires:
        - pip
      commands:
        - pip check
    about:
      home: https://www.pola.rs
      license: MIT
      license_family: MIT
      license_file:
        - polars-runtime-32/LICENSE
        - polars-runtime-32/THIRDPARTY.yml
      summary: Polars is a blazingly fast DataFrames library implemented in Rust using Apache Arrow(2) as memory model.
      description: |
        Polars is a blazingly fast DataFrame library for manipulating structured data. The core is written in Rust, and
        available for Python, R and NodeJS.
        Key features:
        * Fast: Written from scratch in Rust, designed close to the machine and without external dependencies.
        * I/O: First class support for all common data storage layers: local, cloud storage & databases.
        * Intuitive API: Write your queries the way they were intended. Polars, internally, will determine the most efficient way to execute using its query optimizer.
        * Out of Core: The streaming API allows you to process your results without requiring all your data to be in memory at the same time
        * Parallel: Utilities the power of your machine by dividing the workload among the available CPU cores without any additional configuration.
        * Vectorized Query Engine: Using Apache Arrow, a columnar data format, to process your queries in a vectorized manner and SIMD to optimize CPU usage.
      doc_url: https://docs.pola.rs/api/python/stable/reference/index.html
      dev_url: https://github.com/pola-rs/polars
  - name: polars-runtime-64
    script: build_runtime.sh  # [not win]
    script: build_runtime.bat  # [win]
    requirements:
      build:
        - {{ stdlib('c') }}  # [linux]
        - {{ compiler('c') }}  # [linux]
        - {{ compiler('cxx') }}  # [linux]
        - {{ compiler('rust-nightly') }}
        - cargo-auditable
        - cargo-bundle-licenses
      host:
        - pip
        - python
        - maturin >=1.3.2,<2
      run:
        - python
    test:
      imports:
        - _polars_runtime_64
      requires:
        - pip
      commands:
        - pip check
    about:
      home: https://www.pola.rs
      license: MIT
      license_family: MIT
      license_file:
        - polars-runtime-64/LICENSE
        - polars-runtime-64/THIRDPARTY.yml
      summary: Polars is a blazingly fast DataFrames library implemented in Rust using Apache Arrow(2) as memory model.
      description: |
        Polars is a blazingly fast DataFrame library for manipulating structured data. The core is written in Rust, and
        available for Python, R and NodeJS.
        Key features:
        * Fast: Written from scratch in Rust, designed close to the machine and without external dependencies.
        * I/O: First class support for all common data storage layers: local, cloud storage & databases.
        * Intuitive API: Write your queries the way they were intended. Polars, internally, will determine the most efficient way to execute using its query optimizer.
        * Out of Core: The streaming API allows you to process your results without requiring all your data to be in memory at the same time
        * Parallel: Utilities the power of your machine by dividing the workload among the available CPU cores without any additional configuration.
        * Vectorized Query Engine: Using Apache Arrow, a columnar data format, to process your queries in a vectorized manner and SIMD to optimize CPU usage.
      doc_url: https://docs.pola.rs/api/python/stable/reference/index.html
      dev_url: https://github.com/pola-rs/polars
  - name: polars-runtime-compat
    script: build_runtime.sh  # [not win]
    script: build_runtime.bat  # [win]
    requirements:
      build:
        - {{ stdlib('c') }}  # [linux]
        - {{ compiler('c') }}  # [linux]
        - {{ compiler('cxx') }}  # [linux]
        - {{ compiler('rust-nightly') }}
        - cargo-auditable
        - cargo-bundle-licenses
      host:
        - pip
        - python
        - maturin >=1.3.2,<2
      run:
        - python
    test:
      imports:
        - _polars_runtime_compat
      requires:
        - pip
      commands:
        - pip check
    about:
      home: https://www.pola.rs
      license: MIT
      license_family: MIT
      license_file:
        - polars-runtime-compat/LICENSE
        - polars-runtime-compat/THIRDPARTY.yml
      summary: Polars is a blazingly fast DataFrames library implemented in Rust using Apache Arrow(2) as memory model.
      description: |
        Polars is a blazingly fast DataFrame library for manipulating structured data. The core is written in Rust, and
        available for Python, R and NodeJS.
        Key features:
        * Fast: Written from scratch in Rust, designed close to the machine and without external dependencies.
        * I/O: First class support for all common data storage layers: local, cloud storage & databases.
        * Intuitive API: Write your queries the way they were intended. Polars, internally, will determine the most efficient way to execute using its query optimizer.
        * Out of Core: The streaming API allows you to process your results without requiring all your data to be in memory at the same time
        * Parallel: Utilities the power of your machine by dividing the workload among the available CPU cores without any additional configuration.
        * Vectorized Query Engine: Using Apache Arrow, a columnar data format, to process your queries in a vectorized manner and SIMD to optimize CPU usage.
      doc_url: https://docs.pola.rs/api/python/stable/reference/index.html
      dev_url: https://github.com/pola-rs/polars
  - name: {{ name }}
    script: build_polars.sh  # [not win]
    script: build_polars.bat  # [win]
    requirements:
      host:
        - pip
        - python
        - setuptools >=61
        - wheel
      run:
        - python
        - {{ pin_subpackage('polars-runtime-32', exact=True) }}
      run_constrained:
        - numpy >=1.16.0
        - pyarrow >=7.0.0
        - fastexcel >=0.9
        - openpyxl >=3.0.0
        - xlsx2csv >=0.8.0
        - connectorx >=0.3.2
        - deltalake >=1.0.0
        - pyiceberg >=0.7.1
        - altair >=5.4.0
        - great_tables >=0.8.0
        - polars-runtime-64 =={{ version }}
        - polars-runtime-compat =={{ version }}
    # ModuleNotFoundError: No module named 'deltalake'
    # ModuleNotFoundError: No module named 'pyiceberg'
    # _ ERROR collecting gh/py-polars/tests/unit/testing/parametric/strategies/test_utils.py _
    # import file mismatch:
    # imported module 'test_utils' has this __file__ attribute:
    # ModuleNotFoundError: No module named 'kuzu'
    # ModuleNotFoundError: required package 'fastexcel' not found
    # Number of modules are missing like xlsx2csv, fastexcel, connectorx
    # AssertionError: Series are different (values not within tolerance)
    # AssertionError: DataFrames are different (dtypes do not match)
    # [left]: [Int32, UInt32, UInt32]
    # [right]: [Int64, UInt32, UInt32]
    test:
      source_files:
        - gh/py-polars/tests
      imports:
        - polars
      commands:
        - pip check
        - pytest -v gh/py-polars/tests {{ ignore_tests }} {{ deselect_tests }}
      requires:
        - pip
        - pytest
        - flask
        - flask-cors
        - orjson
        - altair
        - pytorch
        - jax
        - hypothesis >=6.97.4
        - polars-runtime-32 =={{ version }}
        - pyarrow
        - pandas
        - boto3
        - sqlalchemy
        - moto
        - pydantic
        - zstandard
        - matplotlib
        - nest-asyncio
        - cloudpickle
        - fsspec
        - gevent
        - openpyxl >=3.0.0
        - pandas
        - hvplot >=0.9.1
        - pyarrow >=7.0.0
        - pydantic >=2.0.0
        - pyxlsb >=1.0  # [py<312]
        - sqlalchemy
        - backports.zoneinfo  # [py<39]
        - tzdata  # [win]
        - xlsxwriter
        - aiosqlite

about:
  home: https://www.pola.rs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Polars is a blazingly fast DataFrames library implemented in Rust using Apache Arrow(2) as memory model.
  description: |
    Polars is a blazingly fast DataFrame library for manipulating structured data. The core is written in Rust, and
    available for Python, R and NodeJS.
    Key features:
    * Fast: Written from scratch in Rust, designed close to the machine and without external dependencies.
    * I/O: First class support for all common data storage layers: local, cloud storage & databases.
    * Intuitive API: Write your queries the way they were intended. Polars, internally, will determine the most efficient way to execute using its query optimizer.
    * Out of Core: The streaming API allows you to process your results without requiring all your data to be in memory at the same time
    * Parallel: Utilities the power of your machine by dividing the workload among the available CPU cores without any additional configuration.
    * Vectorized Query Engine: Using Apache Arrow, a columnar data format, to process your queries in a vectorized manner and SIMD to optimize CPU usage.
  doc_url: https://docs.pola.rs/api/python/stable/reference/index.html
  dev_url: https://github.com/pola-rs/polars

extra:
  recipe-maintainers:
    - borchero
    - Maxyme
    - timkpaine
    - ritchie46
    - sugatoray
    - xhochy
    - dhirschfeld
    - pavelzw
    - 0xbe7a
